name = "portfolio"
main = "worker.js"
compatibility_date = "2026-08-23"

[assets]
directory = "."
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "mezz-portfolio"
database_id = "3ec4d577-7ab5-405f-8c06-b216648bc788"
