name = "mezz-portfolio"
compatibility_date = "2026-08-23"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "mezz-portfolio"
database_id = "3ec4d577-7ab5-405f-8c06-b216648bc788"
